# Generated by Django 3.1.2 on 2020-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101, verbose_name='Video Title')),
                ('description', models.TextField(blank=True)),
                ('publishedAt', models.TimeField()),
                ('thumbnailUrl', models.URLField()),
                ('channelName', models.CharField(max_length=30)),
            ],
        ),
    ]
