# Generated by Django 3.1.2 on 2020-10-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0002_ytapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytapikey',
            name='timesUsed',
            field=models.IntegerField(default=0),
        ),
    ]
