# Generated by Django 3.1.2 on 2020-10-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0003_auto_20201001_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='videoId',
            field=models.CharField(default='gsdsdug', max_length=15),
            preserve_default=False,
        ),
    ]
